vpc-name      = "my-vpc"
igw-name      = "my-internet-gateway"
subnet-name   = "Jenkins-Subnet-New"
rt-name       = "my-route-table"
sg-name       = "launch-wizard-1"
instance-name = "Jenkins-vpc"
key-name      = "hamza-project"
iam-role      = "Admin"